<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProdukSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // gambar gunakan placeholder dan untuk berat,panjang,lebar gunakan int, untuk nama buku sesuaikan dengan kategori dan per kategori berikan 5 buku
        $produk = [
            [ 
                'kode_kategori' => 1,
                'gambar' => 'dummy1.png',
                'judul_buku' => 'Cerpen 1',
                'harga' => 100000,
                'stok' => 10,
                'penulis' => 'Penulis 1',
                'deskripsi' => 'Deskripsi 1. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Eum consequatur aspernatur eveniet, temporibus ipsam neque dolor voluptates qui sequi rem dolore. Dolorum dicta voluptate voluptas omnis doloremque unde adipisci dolorem.',
                'jumlah_halaman' => 100,
                'tanggal_terbit' => '2021-06-15',
                'isbn' => 'ISBN 1',
                'bahasa' => 'Bahasa 1',
                'penerbit' => 'Penerbit 1',
                'berat' => 1,
                'lebar' => 1,
                'panjang' => 1,
            ],
            [
                'kode_kategori' => 1,
                'gambar' => 'dummy2.png',
                'judul_buku' => 'Cerpen 2',
                'harga' => 200000,
                'stok' => 20,
                'penulis' => 'Penulis 2',
                'deskripsi' => 'Deskripsi 2. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Eum consequatur aspernatur eveniet, temporibus ipsam neque dolor voluptates qui sequi rem dolore. Dolorum dicta voluptate voluptas omnis doloremque unde adipisci dolorem.',
                'jumlah_halaman' => 200,
                'tanggal_terbit' => '2021-06-16',
                'isbn' => 'ISBN 2',
                'bahasa' => 'Bahasa 2',
                'penerbit' => 'Penerbit 2',
                'berat' => 2,
                'lebar' => 2,
                'panjang' => 2,
            ],
            [
                'kode_kategori' => 2,
                'gambar' => 'dummy3.png',
                'judul_buku' => 'Novel 1',
                'harga' => 300000,
                'stok' => 30,
                'penulis' => 'Penulis 3',
                'deskripsi' => 'Deskripsi 3. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Eum consequatur aspernatur eveniet, temporibus ipsam neque dolor voluptates qui sequi rem dolore. Dolorum dicta voluptate voluptas omnis doloremque unde adipisci dolorem.',
                'jumlah_halaman' => 300,
                'tanggal_terbit' => '2021-06-17',
                'isbn' => 'ISBN 3',
                'bahasa' => 'Bahasa 3',
                'penerbit' => 'Penerbit 3',
                'berat' => 3,
                'lebar' => 3,
                'panjang' => 3,
            ],
            [
                'kode_kategori' => 2,
                'gambar' => 'dummy4.png',
                'judul_buku' => 'Novel 2',
                'harga' => 400000,
                'stok' => 40,
                'penulis' => 'Penulis 4',
                'deskripsi' => 'Deskripsi 4. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Eum consequatur aspernatur eveniet, temporibus ipsam neque dolor voluptates qui sequi rem dolore. Dolorum dicta voluptate voluptas omnis doloremque unde adipisci dolorem.',
                'jumlah_halaman' => 400,
                'tanggal_terbit' => '2021-06-18',
                'isbn' => 'ISBN 4',
                'bahasa' => 'Bahasa 4',
                'penerbit' => 'Penerbit 4',
                'berat' => 4,
                'lebar' => 4,
                'panjang' => 4,
            ],
            [
                'kode_kategori' => 3,
                'gambar' => 'dummy5.png',
                'judul_buku' => 'Komik 1',
                'harga' => 500000,
                'stok' => 50,
                'penulis' => 'Penulis 5',
                'deskripsi' => 'Deskripsi 5. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Eum consequatur aspernatur eveniet, temporibus ipsam neque dolor voluptates qui sequi rem dolore. Dolorum dicta voluptate voluptas omnis doloremque unde adipisci dolorem.',
                'jumlah_halaman' => 500,
                'tanggal_terbit' => '2021-06-19',
                'isbn' => 'ISBN 5',
                'bahasa' => 'Bahasa 5',
                'penerbit' => 'Penerbit 5',
                'berat' => 5,
                'lebar' => 5,
                'panjang' => 5,
            ],
            [
                'kode_kategori' => 3,
                'gambar' => 'dummy6.png',
                'judul_buku' => 'Komik 2',
                'harga' => 600000,
                'stok' => 60,
                'penulis' => 'Penulis 6',
                'deskripsi' => 'Deskripsi 6. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Eum consequatur aspernatur eveniet, temporibus ipsam neque dolor voluptates qui sequi rem dolore. Dolorum dicta voluptate voluptas omnis doloremque unde adipisci dolorem.',
                'jumlah_halaman' => 600,
                'tanggal_terbit' => '2021-06-20',
                'isbn' => 'ISBN 6',
                'bahasa' => 'Bahasa 6',
                'penerbit' => 'Penerbit 6',
                'berat' => 6,
                'lebar' => 6,
                'panjang' => 6,
            ],
            [
                'kode_kategori' => 4,
                'gambar' => 'dummy7.png',
                'judul_buku' => 'Fiksi 1',
                'harga' => 700000,
                'stok' => 70,
                'penulis' => 'Penulis 7',
                'deskripsi' => 'Deskripsi 7. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Eum consequatur aspernatur eveniet, temporibus ipsam neque dolor voluptates qui sequi rem dolore. Dolorum dicta voluptate voluptas omnis doloremque unde adipisci dolorem.',
                'jumlah_halaman' => 700,
                'tanggal_terbit' => '2021-06-21',
                'isbn' => 'ISBN 7',
                'bahasa' => 'Bahasa 7',
                'penerbit' => 'Penerbit 7',
                'berat' => 7,
                'lebar' => 7,
                'panjang' => 7,
            ],
            [
                'kode_kategori' => 4,
                'gambar' => 'dummy8.png',
                'judul_buku' => 'Fiksi 2',
                'harga' => 800000,
                'stok' => 80,
                'penulis' => 'Penulis 8',
                'deskripsi' => 'Deskripsi 8. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Eum consequatur aspernatur eveniet, temporibus ipsam neque dolor voluptates qui sequi rem dolore. Dolorum dicta voluptate voluptas omnis doloremque unde adipisci dolorem.',
                'jumlah_halaman' => 800,
                'tanggal_terbit' => '2021-06-22',
                'isbn' => 'ISBN 8',
                'bahasa' => 'Bahasa 8',
                'penerbit' => 'Penerbit 8',
                'berat' => 8,
                'lebar' => 8,
                'panjang' => 8,
            ],
            [
                'kode_kategori' => 5,
                'gambar' => 'dummy9.png',
                'judul_buku' => 'Non-Fiksi 1',
                'harga' => 900000,
                'stok' => 90,
                'penulis' => 'Penulis 9',
                'deskripsi' => 'Deskripsi 9. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Eum consequatur aspernatur eveniet, temporibus ipsam neque dolor voluptates qui sequi rem dolore. Dolorum dicta voluptate voluptas omnis doloremque unde adipisci dolorem.',
                'jumlah_halaman' => 900,
                'tanggal_terbit' => '2021-06-23',
                'isbn' => 'ISBN 9',
                'bahasa' => 'Bahasa 9',
                'penerbit' => 'Penerbit 9',
                'berat' => 9,
                'lebar' => 9,
                'panjang' => 9,
            ],
            [
                'kode_kategori' => 5,
                'gambar' => 'dummy10.png',
                'judul_buku' => 'Non-Fiksi 2',
                'harga' => 1000000,
                'stok' => 100,
                'penulis' => 'Penulis 10',
                'deskripsi' => 'Deskripsi 10. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Eum consequatur aspernatur eveniet, temporibus ipsam neque dolor voluptates qui sequi rem dolore. Dolorum dicta voluptate voluptas omnis doloremque unde adipisci dolorem.',
                'jumlah_halaman' => 1000,
                'tanggal_terbit' => '2021-06-24',
                'isbn' => 'ISBN 10',
                'bahasa' => 'Bahasa 10',
                'penerbit' => 'Penerbit 10',
                'berat' => 10,
                'lebar' => 10,
                'panjang' => 10,
            ],
        ];

        foreach ($produk as $item) {
            \App\Models\Produk::create($item);
        }
        
    }
}
